apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inventree.fullname" . }}-server
  labels:
    app: inventree-server
    {{- include "inventree.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: inventree-server
      {{- include "inventree.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: inventree-server
        {{- include "inventree.labels" . | nindent 8 }}
    spec:
      initContainers:
        - image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          name: create-database
          command: ["invoke", "update", "--skip-backup"]
          envFrom:
            - configMapRef:
                name: {{ include "inventree.fullname" . }}-server
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "inventree.fullname" . }}-server
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/inventree/data
          {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName:  {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "inventree.fullname" . }}-data{{ end }}
      {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}